### ISSUE TITLE
Flagging Content Returns User to the Top

### ISSUE THREAD

**Issue by mrjarbenne** [francescolaffi/BP-Moderation#12]
When content is flagged in the Activity Stream, I am now re-directed to the top of the page where a green bar thanks me for my report. In the previous version, the button changed via ajax, so I could continue navigating through the activity stream from the reported content. 

If I have clicked the "Load More" button at the bottom of the Activity Stream on an active community a few times, and am deep into the activity stream, getting returned to the top, rather than keeping my place in the stream, adds an extra few steps to get back to where I want to be on the activity stream. Make sense?

**Comment by francescolaffi** [comment]
the ajax functionality has always been a progressive enhancement, so it works with a normal request and the ajax functionality is used if js is available. So nothing has changed about how the flagging work and it still is supposed to work with ajax. Lets find out why the ajax is not working and its falling back to normal requests.

I'm assuming you have js enabled and you dont have any other problems with other bp ajax operations since you mentioned using 'load more'.

could you check:
- if bp-mod js file get loaded, try searching bp-moderation.js in the page source, you should find a script tag, try to load the url of the js file in another tab and see if it loads correctly
- if the flag link has the class bpm-report-link
- if there are any js errors in your browser console related to bp-moderation

other useful info:
- wp version
- bp version
- theme used

**Comment by mrjarbenne** [comment]
The file seems to load correctly. The Class is correct. There are no js errors.

Upon further testing, it only seems to occur on subsequent activity posts. The ajax works on the first 20, but if I load more, and try to click on one from the next 20 that have loaded, I get pushed back up to the top. 

WP 3.6
BP 1.8.1
Theme: TwentyThirteen Child (just colour changes and a different font)
BPM version 0.1.7

I'll keep poking at it on my end. Should I update to the github version? Are there big differences between that version and the one recently pushed out to the repo?

**Comment by francescolaffi** [comment]
the fact that it doesnt works only on dynamically loaded links was very useful to pinpoint the issue: it only attached to the flag links on pageload, now it uses event delegation so it works even with the links added by other ajax tasks (load more, ajax comments).

the version on the main branch on github doesn't contain any big changes vs 0.1.7 but it contains few fixes, you can see the commit log https://github.com/francescolaffi/BP-Moderation/commits/master and see what was committed after the 0.1.7 (after 2013-07-23). When I get the time to do some pre-release testing on the current dev version I'll release it as 0.1.8. 
On the main branch I don't commit obviously broken code or half done features, but there could still be issues, its not recommended for production, if you use it will be shown as 0.1.8-dev and when 0.1.8 is officially released you'll get the update notification. 
It would be useful to test it especially on issues you reported or care about to see if the fix is working properly.

**Comment by mrjarbenne** [comment]
That's working now.
